[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = 'colorscheme gruvbox'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes', 'gruvbox']
hook_add = '''
    " Powerline系フォントを利用する
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#whitespace#enabled = 0
    " タブバーのカスタマイズを有効にする
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#buffer_idx_mode = 1
    let g:airline#extensions#whitespace#mixed_indent_algo = 1
    " タブバーの右領域を非表示にする
    let g:airline#extensions#tabline#show_splits = 0
    " let g:airline#extensions#tabline#show_tab_type = 0
    " let g:airline#extensions#tabline#show_close_button = 0
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'
depends = ['vim-airline']
hook_add = '''
    " ブランチ情報を表示する
    let g:airline#extensions#branch#enabled = 1
'''
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_exclude_filetypes = ['help', 'nerdtree']
    let g:indent_guides_guide_size = 4
    let g:indent_guides_start_level = 1
'''

#[[plugins]]
#repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('python3')"
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_ignore_case = 1
    let g:deoplete#enable_smart_case = 1
'''

[[plugins]]
repo = 'fidian/hexmode'

[[plugins]]
repo = 'junegunn/fzf.vim'
